const pages = {
 'about.html':['About ImpactJobs','<p class="eyebrow">CAREERS THAT CREATE CHANGE</p><h1>Work with purpose.</h1><p>ImpactJobs by NEIC brings social work, CSR, NGO and development sector opportunities into one place.</p><h2>How it works</h2><ol><li>Search by role, skills, organization or location.</li><li>Read the job details and check the closing date.</li><li>Apply directly through the employer’s application link.</li></ol><p>Listings are maintained by the site team. Employers are responsible for their job descriptions and recruitment decisions.</p><a class="button" href="index.html#jobs">Explore opportunities ↗</a>'],
 'resources.html':['Career resources','<h1>Make your next application count.</h1><h2>Build a focused CV</h2><p>Show your relevant projects, communities served, responsibilities and measurable outcomes. Keep contact details current and tailor your experience to the role.</p><h2>Prepare for development sector interviews</h2><p>Be ready to discuss field experience, stakeholder relationships, safeguarding, project delivery and how you evaluate results. Use specific examples from your work.</p><h2>Before you apply</h2><ul><li>Check the location, contract type and closing date.</li><li>Read the organization’s website and application instructions.</li><li>Verify unexpected requests for money or sensitive documents directly with the organization.</li><li>Keep a copy of the vacancy and your submitted application.</li></ul><a class="button" href="index.html#jobs">Find opportunities ↗</a>'],
 'employers.html':['For employers','<h1>Find people who share your purpose.</h1><p>ImpactJobs features opportunities in social work, CSR, NGOs and the development sector.</p><h2>Prepare your vacancy</h2><p>Include a job title, organization, location, employment type, responsibilities, required skills, closing date and a working application URL. Salary and experience information help candidates assess suitability.</p><h2>Publishing opportunities</h2><p>Listings are currently managed by the NEIC site team. Public self-service submissions are not available. Visit NEIC for its published contact channels and enquiries.</p><a class="button" href="https://neic.in" target="_blank" rel="noopener">Visit NEIC ↗</a><h2>Already coordinating with the team?</h2><p>Share the vacancy details with your existing NEIC contact. The team can publish and update the listing through its connected data sheet.</p>'],
 'advertise.html':['Advertise','<h1>Reach a purpose-driven community.</h1><p>Share relevant training, events, services and opportunities with social work and development sector professionals.</p><h2>Sponsored placements</h2><p>Published campaigns appear above or below the job listings and below job details. Each placement is clearly labelled Sponsored.</p><h2>Prepare your campaign</h2><p>Provide a campaign title, sponsor name, short description, destination URL, optional image and intended start and end dates. Publication is managed by the NEIC team.</p><p>For advertising enquiries, use NEIC’s published contact channels.</p><a class="button" href="https://neic.in" target="_blank" rel="noopener">Visit NEIC ↗</a>'],
 'privacy.html':['Privacy','<h1>Privacy</h1><p>This website loads job listings and sponsored content from a Google Apps Script service. Requests are processed by Google and the website’s hosting provider.</p><h2>Saved jobs</h2><p>Saving a job stores its identifier in your browser’s local storage. No account is required. You can remove saved jobs individually or clear this website’s browser data. Saved jobs do not sync across devices.</p><h2>Applications and external content</h2><p>Applications open employer websites. Those websites have their own privacy policies. Employer logos and advertising images may load from external servers, which receive normal browser request information.</p><h2>Information collected by this site</h2><p>The website does not include registration forms, application uploads, analytics scripts or advertising trackers. Your searches are filtered in your browser and are not submitted to a search service.</p><p>For enquiries about this website, use the contact channels published on <a href="https://neic.in">NEIC’s website</a>.</p>'],
 'terms.html':['Terms of use','<h1>Terms of use</h1><p>ImpactJobs is a job discovery platform. Listings are informational and may change or be withdrawn.</p><h2>Employer information</h2><p>Employers are responsible for their vacancy details, application processes and recruitment decisions. Confirm requirements and availability with the employer before applying.</p><h2>Sponsored content</h2><p>Sponsored placements are labelled. Their presence does not guarantee the advertiser’s services or outcomes.</p><h2>Using the website</h2><p>Use the information responsibly. Do not misrepresent an employer, interfere with the service or misuse other people’s information.</p><p>Contact NEIC through its <a href="https://neic.in">main website</a> with concerns about a listing.</p>'],
 'saved.html':['Saved jobs','<h1>Your saved opportunities</h1><p>Keep your next move in view. Saved jobs stay in this browser.</p><p id="status" role="status">Loading saved jobs…</p><div id="job-list" class="job-grid"></div><button id="more" class="secondary" hidden>Show more jobs</button>'],
 'organizations.html':['Organizations','<p class="eyebrow">MEET YOUR NEXT TEAM</p><h1>Organizations creating change.</h1><p>Explore organizations with current opportunities.</p><div id="organizations" class="job-grid" aria-live="polite">Loading organizations…</div>'],
 '404.html':['Page not found','<h1>This page could not be found.</h1><p>Find your way back to current opportunities.</p><a class="button" href="index.html">Back to home ↗</a>']
};
const fs=require('node:fs');for(const [file,[title,body]]of Object.entries(pages)){fs.writeFileSync(file,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${title} — ImpactJobs by NEIC."><title>${title} | ImpactJobs by NEIC</title><link rel="stylesheet" href="style.css"><script defer src="config.js"></script><script defer src="script.js"></script></head><body><a class="skip" href="#main">Skip to content</a><header id="header"></header><main id="main" class="wrap page ${['saved.html','organizations.html'].includes(file)?'':'content'}">${body}</main><footer id="footer"></footer></body></html>`);}
