'use strict';
const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function url(value) { try { const u = new URL(String(value)); return ['https:','http:'].includes(u.protocol) ? u.href : ''; } catch { return ''; } }
function date(value) { if (!value) return null; const s=String(value).trim(); let m=s.match(/^(\d{4})-(\d{2})-(\d{2})/); if(!m){const d=s.match(/^(\d{2})[-/](\d{2})[-/](\d{4})$/);if(d)m=[d[0],d[3],d[2],d[1]];} if(!m)return null;const result=new Date(+m[1],+m[2]-1,+m[3]); return result.getFullYear()===+m[1]&&result.getMonth()===+m[2]-1&&result.getDate()===+m[3]?result:null; }
function expired(row, field='Expiration Date') { const d=date(row[field]); if(!d)return false; d.setHours(23,59,59,999); return Date.now()>d.getTime(); }
function published(row){return String(row.Status||'').trim().toLowerCase()==='published';}
function displayDate(value){const d=date(value);return d?d.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}):'';}
function normalize(row){return Object.fromEntries(Object.entries(row).map(([k,v])=>[k.trim(),typeof v==='string'?v.trim():v]));}
function payload(data){const jobs=Array.isArray(data)?data:data?.jobs;const ads=Array.isArray(data)?[]:data?.ads??[];if(!Array.isArray(jobs)||!Array.isArray(ads))throw Error('Invalid data response');return {jobs:jobs.filter(x=>x&&typeof x==='object').map(normalize),ads:ads.filter(x=>x&&typeof x==='object').map(normalize)};}
function readSaved(){try{const x=JSON.parse(localStorage.getItem('impactjobs-saved')||'[]');return new Set(Array.isArray(x)?x.filter(v=>typeof v==='string'):[]);}catch{return new Set();}}
let saved=readSaved(),jobs=[],ads=[],limit=12,loading=false,loaded=false,lastUpdated=null,refreshFailed=false;
const route=location.pathname.replace(/\/$/,'').split('/').pop()||'index';
const page=route.endsWith('.html')?route:route+'.html';
$('header').innerHTML='<div class="wrap nav"><a class="brand" href="index.html"><b>↗</b><span>ImpactJobs<small>BY NEIC</small></span></a><nav aria-label="Main navigation"><a href="index.html#jobs">Find jobs</a><a href="organizations.html">Organizations</a><a href="saved.html">Saved jobs</a><a href="about.html">About</a><a class="button secondary" href="employers.html">For employers ↗</a></nav></div>';
$('footer').innerHTML='<div class="wrap"><a class="brand" href="index.html">ImpactJobs<small>BY NEIC</small></a><nav aria-label="Footer"><a href="resources.html">Career resources</a><a href="advertise.html">Advertise</a><a href="privacy.html">Privacy</a><a href="terms.html">Terms</a><a href="https://neic.in" target="_blank" rel="noopener">NEIC ↗</a></nav><p>© '+new Date().getFullYear()+' ImpactJobs by NEIC. Careers that create change.</p></div>';
for(const a of document.querySelectorAll('header nav a'))if(a.getAttribute('href').split('#')[0]===page)a.setAttribute('aria-current','page');
function activeJobs(){return jobs.filter(j=>published(j)&&!expired(j)&&j.Title&&j.ID);}
function saveButton(id){const yes=saved.has(String(id));return `<button class="save secondary" data-save="${esc(id)}" aria-pressed="${yes}">${yes?'Saved ✓':'Save job'}</button>`;}
function avatar(j){const logo=url(j['Company Logo']);return logo?`<img class="avatar" src="${esc(logo)}" alt="" loading="lazy" referrerpolicy="no-referrer">`:`<span class="avatar" aria-hidden="true">${esc(String(j.Company||'IJ').slice(0,2).toUpperCase())}</span>`;}
function card(j){return `<article class="job-card"><div class="card-head">${avatar(j)}<span class="company">${esc(j.Company||'Organization not specified')}</span></div><h3><a href="job.html?id=${encodeURIComponent(j.ID)}">${esc(j.Title)}</a></h3><div class="meta">${esc(j.Location||'Location not specified')}${j.Salary?' · '+esc(j.Salary):''}</div><div>${[j.Category,j['Job Type'],j.Experience].filter(Boolean).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><p class="meta">${expired(j)?'Applications closed':j['Expiration Date']?'Apply by '+esc(displayDate(j['Expiration Date'])):displayDate(j['Date Posted'])?'Posted '+esc(displayDate(j['Date Posted'])):'Closing date not specified'}</p><div class="card-foot"><a href="job.html?id=${encodeURIComponent(j.ID)}">View opportunity ↗</a>${saveButton(j.ID)}</div></article>`;}
function populateFilters(){for(const [id,key,label] of [['category','Category','All categories'],['type','Job Type','All types'],['experience','Experience','Any experience']]){const el=$(id);if(!el)continue;const selected=el.value||new URLSearchParams(location.search).get(id)||'';const values=[...new Set(activeJobs().map(j=>j[key]).filter(Boolean))].sort();if(selected&&!values.includes(selected))values.push(selected);el.innerHTML=`<option value="">${label}</option>`+values.map(v=>`<option>${esc(v)}</option>`).join('');el.value=selected;}}
function renderList(){if(!$('job-list')||!loaded)return;let list=page==='saved.html'?jobs.filter(j=>published(j)&&saved.has(String(j.ID))):activeJobs();if($('query')){const q=$('query').value.trim().toLowerCase(),l=$('location').value.trim().toLowerCase();list=list.filter(j=>[j.Title,j.Company,j['Required Skills'],j['Job Description']].join(' ').toLowerCase().includes(q)&&String(j.Location||'').toLowerCase().includes(l)&&['category','type','experience'].every((id,i)=>!$(id).value||String(j[['Category','Job Type','Experience'][i]]||'').toLowerCase()===$(id).value.toLowerCase()));}
const sort=$('sort')?.value;list.sort((a,b)=>sort==='deadline'?(date(a['Expiration Date'])?.getTime()??Infinity)-(date(b['Expiration Date'])?.getTime()??Infinity):(date(b['Date Posted'])?.getTime()||0)-(date(a['Date Posted'])?.getTime()||0));
$('job-list').innerHTML=list.length?list.slice(0,limit).map(card).join(''):`<div class="empty"><h3>${page==='saved.html'?'No saved opportunities available':'No matching opportunities'}</h3><p>${page==='saved.html'?'Save jobs while browsing to find them here. Unpublished or removed jobs no longer appear.':'Try another search or check back for new published jobs.'}</p><a href="index.html#jobs">Browse opportunities →</a></div>`;
if($('status'))$('status').textContent=`${list.length} ${list.length===1?'opportunity':'opportunities'} · Updated ${(lastUpdated||new Date()).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}`;if(refreshFailed&&$('status'))$('status').innerHTML+='<div class="notice" role="alert">Unable to refresh. Previously loaded information is shown. <button class="secondary" data-retry>Retry</button></div>';if($('more'))$('more').hidden=list.length<=limit;
}
function renderCategories(){if(!$('categories'))return;const values=[...new Set(['Social Work','CSR','NGO','Education','Public Health','Research',...activeJobs().map(j=>j.Category).filter(Boolean)])];$('categories').innerHTML=values.map(v=>`<a class="category" href="index.html?category=${encodeURIComponent(v)}#jobs">${esc(v)} <span>↗</span></a>`).join('');}
function renderOrganizations(){if(!$('organizations'))return;const groups=new Map();for(const j of activeJobs()){if(j.Company)groups.set(j.Company,(groups.get(j.Company)||0)+1);} $('organizations').innerHTML=groups.size?[...groups].sort((a,b)=>a[0].localeCompare(b[0])).map(([name,n])=>`<a class="panel" href="index.html?q=${encodeURIComponent(name)}#jobs"><h3>${esc(name)}</h3><p>${n} open ${n===1?'opportunity':'opportunities'} ↗</p></a>`).join(''):'<p>No organizations with open jobs yet.</p>';}
function renderAds(){for(const placement of ['top','bottom']){const el=$('ads-'+placement);if(!el)continue;const list=ads.filter(a=>published(a)&&a.Title&&url(a['Target URL'])&&!expired(a,'End Date')&&(!date(a['Start Date'])||date(a['Start Date']).getTime()<=Date.now())&&(String(a.Placement||'bottom').toLowerCase()===placement||a.Placement==='all'));el.hidden=!list.length;el.innerHTML=list.map(a=>`<a class="ad" href="${esc(url(a['Target URL']))}" target="_blank" rel="sponsored noopener noreferrer"><small>SPONSORED${a.Sponsor?' · '+esc(a.Sponsor):''}</small>${url(a['Image URL'])?`<img src="${esc(url(a['Image URL']))}" loading="lazy" alt="${esc(a.Title)}" referrerpolicy="no-referrer">`:''}<h3>${esc(a.Title)}</h3>${a.Description?`<p>${esc(a.Description)}</p>`:''}<span>${esc(a['CTA Text']||'Learn more')} ↗</span></a>`).join('');}}
function renderDetail(){if(!$('detail'))return;const id=new URLSearchParams(location.search).get('id');const j=jobs.find(j=>String(j.ID)===id&&published(j));if(!j){$('detail').innerHTML='<div class="empty"><h1>Job not available</h1><p>This link may be incorrect, or the opportunity has been removed.</p><a href="index.html#jobs">Browse current jobs →</a></div>';return;}document.title=`${j.Title} at ${j.Company} | ImpactJobs`;const apply=url(j['Apply URL']);const website=url(j['Company Website']);$('detail').innerHTML=`<div class="detail-head"><p class="eyebrow">${esc(j.Company)}</p><h1>${esc(j.Title)}</h1><p>${esc(j.Location||'Location not specified')} ${j['Job Type']?' · '+esc(j['Job Type']):''}</p>${saveButton(j.ID)}</div><div class="detail-grid"><article class="panel">${[['Job description','Job Description'],['Required skills & experience','Required Skills'],['What the employer offers','What We Offer']].filter(([,key])=>j[key]).map(([label,key])=>`<h2>${label}</h2><p class="prose">${esc(j[key])}</p>`).join('')||'<p>The employer has not provided a description.</p>'}<h2>Share this opportunity</h2><button class="secondary" id="share">Copy job link</button><p id="share-status" role="status"></p></article><aside><section class="panel"><h2>At a glance</h2>${[['Location','Location'],['Employment','Job Type'],['Category','Category'],['Experience','Experience'],['Salary','Salary'],['Posted','Date Posted'],['Apply by','Expiration Date']].filter(([,key])=>j[key]).map(([label,key])=>`<p><strong>${label}</strong><br>${esc(key.includes('Date')?displayDate(j[key]):j[key])}</p>`).join('')}${expired(j)?'<p class="notice">Applications for this opportunity have closed.</p>':apply?`<a class="button" href="${esc(apply)}" target="_blank" rel="noopener noreferrer">Apply with employer ↗</a>`:'<p class="notice">An application link has not been provided.</p>'}<p class="meta">Review the employer’s requirements before applying. Applications are handled by the employer.</p></section><section class="panel"><h2>About the organization</h2><strong>${esc(j.Company)}</strong>${j['Company Address']?`<p>${esc(j['Company Address'])}</p>`:''}${website?`<p><a href="${esc(website)}" target="_blank" rel="noopener noreferrer">Visit organization website ↗</a></p>`:''}${j['Company Email']?`<p class="prose">${esc(j['Company Email'])}</p>`:''}</section></aside></div>`;}
async function load(){if(loading)return;loading=true;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const res=await fetch(SITE_CONFIG.apiUrl,{signal:controller.signal,cache:'no-store',redirect:'follow'});if(!res.ok)throw Error('HTTP '+res.status);const data=payload(await res.json());jobs=data.jobs;ads=data.ads;loaded=true;lastUpdated=new Date();refreshFailed=false;populateFilters();renderList();renderCategories();renderOrganizations();renderDetail();renderAds();}catch(e){refreshFailed=true;const message=loaded?'Unable to refresh. Previously loaded information is shown; retry for current availability.':'We could not load opportunities. Please try again shortly.';const retry=`<div class="notice" role="alert">${message} <button class="secondary" data-retry>Retry</button></div>`;if($('status'))$('status').innerHTML=retry;if($('detail')){const old=$('detail').querySelector?.('.refresh-error');old?.remove();if(!loaded)$('detail').innerHTML=retry;else $('detail').insertAdjacentHTML('afterbegin','<div class="refresh-error">'+retry+'</div>');}if($('organizations')){if(!loaded)$('organizations').innerHTML=retry;else {const old=$('organizations').querySelector?.('.refresh-error');old?.remove();$('organizations').insertAdjacentHTML('afterbegin','<div class="refresh-error">'+retry+'</div>');}}for(const id of ['ads-top','ads-bottom'])if($(id))$(id).hidden=true;console.warn('ImpactJobs data unavailable:',e.message);}finally{clearTimeout(timer);loading=false;}}
document.addEventListener('click',async event=>{const save=event.target.closest('[data-save]');if(save){const id=save.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);try{localStorage.setItem('impactjobs-saved',JSON.stringify([...saved]));}catch{saved=readSaved();alert('Your browser could not save this job. Allow local storage and try again.');}renderList();renderDetail();}if(event.target.closest('[data-retry]'))load();if(event.target.closest('#share')){try{await navigator.clipboard.writeText(location.href);$('share-status').textContent='Job link copied.';}catch{$('share-status').textContent='Copy this link: '+location.href;}}});
if($('search-form')){$('query').value=new URLSearchParams(location.search).get('q')||'';$('search-form').addEventListener('submit',e=>{e.preventDefault();limit=12;renderList();$('jobs').scrollIntoView({behavior:'smooth'});});for(const id of ['category','type','experience','sort'])$(id).addEventListener('change',()=>{limit=12;renderList();});$('clear').addEventListener('click',()=>{for(const id of ['query','location','category','type','experience'])$(id).value='';$('sort').value='newest';history.replaceState(null,'',location.pathname+'#jobs');limit=12;renderList();});}
$('more')?.addEventListener('click',()=>{limit+=12;renderList();});
if($('job-list')||$('detail')||$('organizations')){renderCategories();load();setInterval(()=>{if(!document.hidden)load();},SITE_CONFIG.refreshMs);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});}
