const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const elements=new Map();const el=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',value:'',hidden:false,addEventListener(){}});return elements.get(id);};
const context=vm.createContext({console,URL,URLSearchParams,Date,Set,Map,AbortController,setTimeout,clearTimeout,setInterval(){},location:{pathname:'/about.html',search:'?id=two',href:'https://test/job.html?id=two'},localStorage:{getItem:()=>null},document:{getElementById:id=>['header','footer'].includes(id)?el(id):null,querySelectorAll:()=>[],addEventListener(){}},window:{}});
vm.runInContext(fs.readFileSync('script.js','utf8'),context);const run=s=>vm.runInContext(s,context);
assert.equal(run("url('javascript:alert(1)')"),'');assert.equal(run("url('data:text/html,hi')"),'');assert.equal(run("url('https://example.org/apply')"),'https://example.org/apply');assert.equal(run("esc('<img onerror=bad>')"),'&lt;img onerror=bad&gt;');
assert.equal(run("date('2026-02-30')"),null);assert.equal(run("displayDate('14-09-2026')"),'14 Sept 2026');assert.equal(run("published({Status:' Draft '})"),false);assert.equal(run("published({Status:' Published '})"),true);
assert.throws(()=>run("payload({error:'unavailable'})"));assert.equal(run("payload([{ID:'x'}]).jobs.length"),1);assert.equal(run("payload({jobs:[],ads:[]}).ads.length"),0);
run("jobs=[{ID:'one',Title:'One',Status:'Published','Expiration Date':'2000-01-01'},{ID:'two',Title:'Two',Status:'Published',Company:'Team','Apply URL':'javascript:alert(1)','Job Description':'<script>bad</script>'},{ID:'three',Title:'Three',Status:'Draft'}]");assert.equal(run('activeJobs().length'),1);
context.document.getElementById=id=>el(id);run('renderDetail()');assert.match(el('detail').innerHTML,/Two/);assert.doesNotMatch(el('detail').innerHTML,/Apply with employer/);assert.match(el('detail').innerHTML,/&lt;script&gt;/);
run("ads=[{Title:'Live campaign',Status:'Published','Target URL':'https://example.org',Placement:'top'},{Title:'Draft campaign',Status:'Draft','Target URL':'https://example.org',Placement:'top'},{Title:'Old campaign',Status:'Published','Target URL':'https://example.org',Placement:'top','End Date':'2000-01-01'}];renderAds()");assert.equal(el('ads-top').hidden,false);assert.match(el('ads-top').innerHTML,/Live campaign/);assert.doesNotMatch(el('ads-top').innerHTML,/Draft campaign|Old campaign/);assert.equal(el('ads-bottom').hidden,true);
run("ads=[];renderAds()");assert.equal(el('ads-top').hidden,true);
run("loaded=true;jobs=[{ID:'a',Title:'Field Officer',Company:'One',Status:'Published',Category:'Social Work',Location:'Delhi','Job Type':'Full Time'},{ID:'b',Title:'CSR Manager',Company:'Two',Status:'Published',Category:'CSR',Location:'Mumbai','Job Type':'Contract'}]");
el('category').value='CSR';run('renderList()');assert.match(el('job-list').innerHTML,/CSR Manager/);assert.doesNotMatch(el('job-list').innerHTML,/Field Officer/);
el('category').value='';el('location').value='Delhi';run('renderList()');assert.match(el('job-list').innerHTML,/Field Officer/);assert.doesNotMatch(el('job-list').innerHTML,/CSR Manager/);
el('location').value='';el('query').value='no match';run('renderList()');assert.match(el('job-list').innerHTML,/No matching opportunities/);
run("saved.add('a')");assert.match(run("saveButton('a')"),/aria-pressed="true"/);
for(const file of fs.readdirSync('.').filter(f=>f.endsWith('.html'))){const html=fs.readFileSync(file,'utf8');for(const match of html.matchAll(/(?:href|src)="([^"]+)"/g)){const dest=match[1].split(/[?#]/)[0];if(dest&&!/^[a-z]+:/i.test(dest))assert.ok(fs.existsSync(dest),`${file}: missing ${dest}`);}assert.doesNotMatch(html,/href="#"/);}
console.log('PASS: safe links, escaping, publication rules, dates, API formats, correct detail ID, unavailable applications, scheduled ads, empty ad removal, local page links.');
